### ISSUE TITLE
error when ran train mode and plot PFM logo

### ISSUE THREAD

**Issue by huijfeng** [deepclip/deepclip#4]
Making PFMs based on convolutional filters
Traceback (most recent call last):
  File "/home/bin/DeepCLIP.py", line 1388, in <module>
    main()
  File "/home/bin/DeepCLIP.py", line 1127, in main
    args.predict_PFM_file, args.draw_seq_logos)
  File "making_CNN_PFMs.py", line 98, in convolutional_logos
    ddd = printing_seq_logo(lg, tttt[i][ii], name= path + '_filter_'+str(FILTER_SIZES[i] / len(VOCAB))+'bp_number'+str(ii+1)+'_score-')
NameError: global name 'path' is not defined

**Comment by thomaskd** [comment]
Hi Huijuan

Thanks for raising the issue :)
For the moment this option only works in prediction mode so that different sequence inputs can be used for logo generation.
So if you run the logo generation with the trained model in prediction mode with a combination of positive and negative training sequences (e.g. `cat pos.fa neg.fa > all.fa`), it should work.

I will keep the issue open until we have corrected this.

Best,
Thomas

**Comment by huijfeng** [comment]
Hi Thomas,
Thanks for your prompt reply. Can I make a suggestion? For train mode, if using --draw_seq_logos, will get that error and the pfms.json file will not be generated coz this error. And I will have to run it all again without this option to just get the pfms.json file. I think it would be better to write this file before try to generate the logo. 
Best,
Huijuan
