### ISSUE TITLE
Error when running bed.py

### ISSUE THREAD

**Issue by Antidington** [deepclip/deepclip#9]
I use `bed.py` to construct a set of binding sites and background sequences but falied:
```bash
(deepclip) ubuntu@VM-0-7-ubuntu:~/deepclip$ python2 bed.py TAIR.HLP1.lncRNA/TAIR.HLP1.bindingsites.bed TAIR.HLP1.lncRNA/TAIR10.chr.fa TAIR.HLP1.lncRNA/A.tha.lncRNA-PLncDB.gtf TAIR.HLP1.pos.fa TAIR.HLP1.neg.fa
 Reading primary peaks from BED file
 Reading GTF file from TAIR.HLP1.lncRNA/A.tha.lncRNA-PLncDB.gtf
 No 'gene' features in GTF, building gene intervals from exons instead.
 Loaded 749 total genes.
(' Reading genome from file TAIR.HLP1.lncRNA/TAIR10.chr.fa ...',)
done
 Filtering and constructing background...
Traceback (most recent call last):
  File "bed.py", line 303, in <module>
    main()
  File "bed.py", line 273, in main
    pos_seqs, neg_seqs, seq_ids = produce_sequences(args.input_file, args.fasta_file, args.gtf_file, args.min_length, args.max_length, args.width, args.padding, args.compatible)
  File "bed.py", line 237, in produce_sequences
    pos_seq = Seq(str(genome[peak.iv.chrom][peak.iv.start:peak.iv.end].seq), generic_dna)
NameError: global name 'generic_dna' is not defined
```
Is there any suggestion?
Many thanks!

**Comment by Antidington** [comment]
Maybe I found where disrupted.
In `bed.py`, line4 was commented:
```python
#from Bio.Alphabet import generic_dna
```
I cancel this comment and run successfully.

**Comment by thomaskd** [comment]
Thanks for raising the issue, seems to be an error that was introduced when porting to python3 and this file wasn't updated fully in the repository.  It should be fixed now, and I'm glad you were able to resolve this issue on your end in the meantime.
